# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1290, 1035)
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(9)
        mainWindow.setFont(font)
        mainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        mainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        mainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 330, 121, 81))
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 57 28pt \"文泉驿正黑\";\n"
"color: rgb(255, 85, 127);")
        self.label.setObjectName("label")
        self.label_face = QtWidgets.QLabel(self.centralwidget)
        self.label_face.setGeometry(QtCore.QRect(720, 460, 451, 441))
        self.label_face.setStyleSheet("\n"
"background-color: rgb(230, 255, 251);")
        self.label_face.setText("")
        self.label_face.setObjectName("label_face")
        self.tableWidget_kind = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_kind.setGeometry(QtCore.QRect(110, 420, 351, 251))
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.tableWidget_kind.setFont(font)
        self.tableWidget_kind.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_kind.setAutoFillBackground(True)
        self.tableWidget_kind.setStyleSheet("font: 57 20pt \"文泉驿正黑\";\n"
"")
        self.tableWidget_kind.setObjectName("tableWidget_kind")
        self.tableWidget_kind.setColumnCount(1)
        self.tableWidget_kind.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_kind.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_kind.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_kind.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_kind.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_kind.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(14)
        item.setFont(font)
        item.setBackground(QtGui.QColor(208, 255, 253))
        self.tableWidget_kind.setHorizontalHeaderItem(0, item)
        self.tableWidget_kind.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_kind.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(620, 30, 631, 291))
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setStyleSheet("font: 57 20pt \"文泉驿正黑\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.pushButton_reok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reok.setGeometry(QtCore.QRect(810, 350, 261, 61))
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_reok.setFont(font)
        self.pushButton_reok.setAutoFillBackground(False)
        self.pushButton_reok.setStyleSheet("background-color: rgb(194, 197, 255);\n"
"font: 57 24pt \"文泉驿正黑\";\n"
"color: rgb(170, 170, 255);")
        self.pushButton_reok.setObjectName("pushButton_reok")
        self.pushButton_print = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_print.setGeometry(QtCore.QRect(80, 720, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Sinhala")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_print.setFont(font)
        self.pushButton_print.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_print.setAutoFillBackground(False)
        self.pushButton_print.setStyleSheet("font: 75 22pt \"Noto Sans Sinhala\";\n"
"border-color: rgb(36, 74, 113);")
        self.pushButton_print.setObjectName("pushButton_print")
        self.pushButton_pay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pay.setGeometry(QtCore.QRect(310, 720, 191, 161))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Sinhala")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_pay.setFont(font)
        self.pushButton_pay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pay.setStyleSheet("font: 75 22pt \"Noto Sans Sinhala\";\n"
"border-color: rgb(97, 97, 145);")
        self.pushButton_pay.setObjectName("pushButton_pay")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 561, 341))
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "果蔬电子秤"))
        mainWindow.setAccessibleName(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">购物车</span></p></body></html>"))
        self.label.setText(_translate("mainWindow", "购物车"))
        item = self.tableWidget_kind.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "类别"))
        item = self.tableWidget_kind.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "名称"))
        item = self.tableWidget_kind.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "重量(g)"))
        item = self.tableWidget_kind.verticalHeaderItem(3)
        item.setText(_translate("mainWindow", "单价(元/kg)"))
        item = self.tableWidget_kind.verticalHeaderItem(4)
        item.setText(_translate("mainWindow", "总价(元)"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("mainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("mainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("mainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("mainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("mainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("mainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("mainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "类别"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "单价"))
        self.pushButton_reok.setText(_translate("mainWindow", "确认所选果蔬"))
        self.pushButton_print.setText(_translate("mainWindow", "打印条形码"))
        self.pushButton_pay.setText(_translate("mainWindow", "二维码付款"))
        self.label_2.setText(_translate("mainWindow", "基于树莓派的果蔬电子秤"))

